notifications:
  email: false

language: php

php:
  - '5.6'
  - '7.0'
  - hhvm

install:
  - composer install

script:
  - ./vendor/bin/phpunit --bootstrap ./vendor/autoload.php  tests/unit/
  - ./vendor/bin/behat --config=./behat.yml